# Generated by Django 2.1.7 on 2019-03-02 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_event_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='user',
        ),
    ]
